### ISSUE TITLE
Pagination goes weird when there are no matches for a search

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/package-frontend#104]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages/search?q=afjdkslfjdsk

### What's your issue?

When there are no results to display, the pagination widget reports `Showing 1 to 0 of NaN entries`.

### Which OS/Browser/Version does this happen on?

All.

### Steps to Reproduce/Additional Details:

Mash your keyboard in the search field and hit <kbd>Enter</kbd>.

**Comment by confused-Techie** [comment]
Thanks a ton for reporting this, I'll try taking a look into it, to see if this is an issue with the backend or frontend.

Since absolutely the frontend should ensure that doesn't happen and things like `NaN` are the frontend's fault, I also want to make sure the backend isn't returning bad data causing this

**Comment by confused-Techie** [comment]
So checking on this, seems the backend is submitting some bad data here when the search leaves zero results.

Specifically:

```
Link: "undefined"
Query-Total: "undefined"
Query-Limit: "undefined"
```

So this issue will likely need changes in both locations to resolve this one

**Comment by confused-Techie** [comment]
So I just wanted to mention, thought further review, this error is not of the fault of the frontend.

We can see for example during the [package viewing](https://web.pulsar-edit.dev/packages?serviceType=consumed&service=tree-vieww), if there are no results the pagination still has valid values. So this issue is only applicable on this one endpoint.

**Comment by savetheclocktower** [comment]
I've still got a UI quibble about showing the pagination at all in that scenario. It's not like `Showing 1 to 0 of 0 entries` makes much more sense than `Showing 1 to 0 of NaN entries`.

I fully realize how insignificant this issue is.

**Comment by confused-Techie** [comment]
@savetheclocktower No that's still a valid point.

So you think showing a static message, such as `No packages found` or `This request doesn't match any packages` makes more sense? Or of course we can go with the static `No Results` return

**Comment by savetheclocktower** [comment]
Yeah, I'd just hide the pagination altogether and show a static message.

**Comment by confused-Techie** [comment]
@savetheclocktower What do you think of this?
![image](https://github.com/pulsar-edit/package-frontend/assets/26921489/cf08985a-6e33-4b48-867c-f39a88afac68)

**Comment by savetheclocktower** [comment]
Works for me.
