### ISSUE TITLE
Packages page 10 encountered an error

### ISSUE THREAD

**Issue by zhaolinlau** [pulsar-edit/package-frontend#115]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages?page=10

### What's your issue?

Unable to view page 10

**Comment by confused-Techie** [comment]
I've gone ahead and transferred this issue to the correct repository.

Thanks a ton for reporting this

**Comment by confused-Techie** [comment]
So looking through this, it seems the issue stems from `js-hyperclick`. Where the package frontend expects that a `repository` field will be available within the package's `package.json` but it isn't present here. We will need to add a fallback if this falls to retrieve the repository info from the package backends native `repository` key, since the backend already accounts for this possibility, where the frontend does not.

Again thanks a ton for reporting this
