### ISSUE TITLE
Download links are broken

### ISSUE THREAD

**Issue by nsartor** [pulsar-edit/package-frontend#71]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://pulsar-edit.dev/download.html

### What's your issue?

The  Cirrus CI binaries are broken _except_ for Windows and the Mac dmg files. The site is returning the following JSON:
```json
{"message":"Invalid Download Parameters provided."}
```
Sample URLs:
https://web.pulsar-edit.dev/download?os=linux&type=linux_deb
https://web.pulsar-edit.dev/download?os=linux&type=linux_appimage

### Which OS/Browser/Version does this happen on?

 Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0

### Steps to Reproduce/Additional Details:

Go to https://pulsar-edit.dev/download.html
Scroll down to Cirrus CI downloads
Select any download other than Mac dmg or Windows

**Comment by confused-Techie** [comment]
I've transferred this issue to the `package-frontend` since this is where the code for the actual download endpoint exists.

While I was hoping I'd keep up more in the website repo to still see this and fix it in a timely manner, that has obviously not been the case. 

So moving it here in hopes it can get better visibility and get fixed.

**Comment by Spiker985** [comment]
Update: Since this has come over to a new repo, we did fix this previously where an entire _build_ was re-run, however, this still occurs when an individual _task_ is re-run. 

Earlier today, @DeeDeeG proposed a code change in the [discord](https://discord.com/channels/992103415163396136/992110095641088001/1074130615558996019) that should also fix the task segment.

@DeeDeeG If you can, please refer to this issue in your PR <3
