### ISSUE TITLE
Some repos contain `git+` in the URL which isn't handled correctly

### ISSUE THREAD

**Issue by Daeraxa** [pulsar-edit/package-frontend#84]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages/simplified-chinese-menu

### What's your issue?

The repo link (and user) are set to `git+https://github.com/chinakids/atom-simplified-chinese-menu.git` which (obviously) isn't a valid URL in a browser.

The `git+` probably needs to be identified and trimmed.

### Which OS/Browser/Version does this happen on?

Win 10 FF 110.0.1

### Steps to Reproduce/Additional Details:

Part of the returned JSON from the API:

```
      "repository": {
        "url": "git+https://github.com/chinakids/atom-simplified-chinese-menu.git",
        "type": "git"
      },
```

**Comment by confused-Techie** [comment]
So I took a look at this, with the plan to utilize the same logic `git` itself uses to parse a URL, so that way we could support everything that git does without any issue.

But after taking a look at the source code of `gits` [`urlmatch.c`](https://github.com/git/git/blob/master/urlmatch.c) and the [test file for this file](https://github.com/git/git/blob/master/t/t0110-urlmatch-normalization.sh) it turns out the logic they use is far more complicated than I was originally prepared for, basing the logic off several RFCs and other backwards compatible standards. 

So this may be a bit more difficult that I had originally hoped for, while we could simply to `.replace("git+", "")` I would like to find a much more sure fire solution that won't break constantly as we find new ways people defined their data.

So if you know any good resources here, such as at least a much more clear test file, that'd be awesome, or I may take some time reading through NPM's source to at least utilize their methodology, but otherwise if this issue seems to be causing real concern we can always move forward with the fast fix I mentioned above.

Just a small update on the plan here, but I am attempting to address this issue, which again, thanks for pointing out

**Comment by savetheclocktower** [comment]
If it's that complex, someone's sure to have written a library we can use to parse them, right? :)

**Comment by confused-Techie** [comment]
You know, @savetheclocktower initially I was somewhat against adding a dependency for something I originally didn't feel was warranted, but you are totally right. It's the only thing that makes sense in this situation, and I've found [`parse-github-url`](https://github.com/jonschlinkert/parse-github-url) which looks like it might fit the bill perfectly.

Loads of tests, zero dependencies, and while not the most active, like I said zero dependencies, so no worries of out of date dep vulnerabilities. 

So appreciate you chiming in here, got me to look for this, which I hope will be a huge help on the backend and frontend
