### ISSUE TITLE
README contents aren't updated after new package version is published

### ISSUE THREAD

**Issue by savetheclocktower** [pulsar-edit/package-frontend#91]
### Thanks in advance for your bug report!

- [X] Have you reproduced this issue in incognito/private browsing?
- [X] Have you made sure you issue doesn't already exist?

### Where is the URL that this occurs?

https://web.pulsar-edit.dev/packages/calculator-light-ui

### What's your issue?

The README contents shown on this page are stale. I've published at least one new version since the README has been updated, but the change are not reflected on the page.

### Which OS/Browser/Version does this happen on?

N/A

**Comment by confused-Techie** [comment]
@savetheclocktower When's the last time you were able to replicate this behavior?

Since when you published this new version back in February, there was still a bug that wouldn't update the package's main metadata fields (including the Readme) properly. This has since been resolved in [package-backend#126](https://github.com/pulsar-edit/package-backend/pull/126), but at the time you would've been affected by this bug.

Since at least for me personally, when publishing new package versions, the readme updates just like I'd expect

**Comment by savetheclocktower** [comment]
Yup, works fine now. I looked through the issues to see if this had been reported, but I didn't think to look through the PRs. Thanks!

**Comment by confused-Techie** [comment]
Yeah no worries, glad this one was already fixed. But does remind me to try and resolve some of these retroactively lol
